name: eslint-check

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [15.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - name: install dependencies
        run: |
          make install
        env:
          CI: true
      - name: run linter
        run: |
          make lint